---
title: "cluster-test"
author: "Jasmine Kobayashi"
format: html
---
```{r , message=FALSE, warning=FALSE}
library(stats)  ## for dist
#https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/dist

## There are many clustering libraries
#install.packages("NbClust")
library(NbClust)
library(cluster)
library(mclust)

library(amap)  ## for using Kmeans (notice the cap K)

library(factoextra) ## for cluster vis, silhouette, etc.
library(purrr)

#install.packages("stylo")
library(stylo)  ## for dist.cosine
#install.packages("philentropy")
library(philentropy)  ## for distance() which offers 46 metrics
## https://cran.r-project.org/web/packages/philentropy/vignettes/Distances.html
library(SnowballC)
library(caTools)
library(dplyr)
library(textstem)
library(stringr)
library(wordcloud)
library(tm) ## to read in corpus (text data)
```

```{r}
(df <- read.csv('../data/API-NOAA/1990-2018_df.csv'))
```
```{r load data}
df <- read.csv("../data/final_combined_df.csv")
```

```{r label vs data}
# suggested label columns
label_cols <-  c('EMXP','PRCP')
class_label_col <- c('EMXP_class')
# data columns
data_cols  <-  c('co2','methane','nitrous_oxide','co2_per_capita','methane_per_capita',
             'nitrous_oxide_per_capita','total_ghg','ghg_per_capita','co2_growth_abs',
             'consumption_co2','consumption_co2_per_capita','energy_per_capita',
             'primary_energy_consumption')
# change class label to factor datatype
df$EMXP_class <- as.factor(df$EMXP_class)


## selecting columns of data
df <- df %>% select(all_of(data_cols))
# labels <- df %>% select(all_of(label_cols))
```
```{r}
dist_cos_df <- distance(as.matrix(scale(t(df))), method="cosine",use.row.names = TRUE)
dist_cos_df <- as.dist(dist_cos_df)
```


```{r}
(HClust_noaa <- hclust(dist_cos_df, method='ward.D'))
```
```{r}
plot(HClust_noaa, main = "Hierarchical Clustering with Cos-sim")
#rect.hclust(HClust_noaa, k=4)
```

