---
title: "cluster-test"
author: "Jasmine Kobayashi"
format: html
---
```{r , message=FALSE, warning=FALSE}
library(stats)  ## for dist
#https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/dist

## There are many clustering libraries
#install.packages("NbClust")
library(NbClust)
library(cluster)
library(mclust)

library(amap)  ## for using Kmeans (notice the cap K)

library(factoextra) ## for cluster vis, silhouette, etc.
library(purrr)

#install.packages("stylo")
library(stylo)  ## for dist.cosine
#install.packages("philentropy")
library(philentropy)  ## for distance() which offers 46 metrics
## https://cran.r-project.org/web/packages/philentropy/vignettes/Distances.html
library(SnowballC)
library(caTools)
library(dplyr)
library(textstem)
library(stringr)
library(wordcloud)
library(tm) ## to read in corpus (text data)
```

```{r}
(df <- read.csv('1990-2018_df.csv'))
```

```{r}
dist_cos_df <- distance(as.matrix(scale(t(df))), method="cosine",use.row.names = TRUE)
dist_cos_df <- as.dist(dist_cos_df)
```


```{r}
(HClust_noaa <- hclust(dist_cos_df, method='ward.D'))
```
```{r}
plot(HClust_noaa, main = "Hierarchical Clustering with Cos-sim")
#rect.hclust(HClust_noaa, k=4)
```

